# docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16-debian
    ports:
      - "3001:3001"
    volumes:
      - ./uptime-kuma:/app/data
    restart: always

